sudo: required

language: php

php:
  - 7

services:
  - rabbitmq

before_script:
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - git clone https://github.com/pdezwart/php-amqp.git
  - cd php-amqp
  - phpize
  - ./configure
  - make
  - sudo make install
  - cd ..
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update
  - sudo rabbitmqctl add_vhost /humus-amqp-test
  - sudo rabbitmqctl set_permissions -p /humus-amqp-test guest ".*" ".*" ".*"

script:
  - php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

after_success:
  - php vendor/bin/coveralls -v
